//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XandaPOS.Edmx
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class XANDA_POSEntities : DbContext
    {
        public XANDA_POSEntities()
            : base("name=XANDA_POSEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<POS_BRAND_MASTER> POS_BRAND_MASTER { get; set; }
        public virtual DbSet<POS_COMPANY_MASTER> POS_COMPANY_MASTER { get; set; }
        public virtual DbSet<POS_CUSTOMER_MASTER> POS_CUSTOMER_MASTER { get; set; }
        public virtual DbSet<POS_EMPLOYEE_MASTER> POS_EMPLOYEE_MASTER { get; set; }
        public virtual DbSet<POS_MASTER_TABLE_HELPER> POS_MASTER_TABLE_HELPER { get; set; }
        public virtual DbSet<POS_PRODUCT_GROUP_MASTER> POS_PRODUCT_GROUP_MASTER { get; set; }
        public virtual DbSet<POS_PRODUCT_MASTER> POS_PRODUCT_MASTER { get; set; }
    }
}
