//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XandaPOS.Edmx
{
    using System;
    using System.Collections.Generic;
    
    public partial class POS_CUSTOMER_MASTER
    {
        public int cust_id { get; set; }
        public string cust_name { get; set; }
        public string cust_addr { get; set; }
        public string cust_pin { get; set; }
        public string cust_phn { get; set; }
    }
}
