//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XandaPOS.Edmx
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class POS_PRODUCT_GROUP_MASTER
    {
        public string prod_grp_id { get; set; }

        [Required(ErrorMessage = "Please enter a valid Product Group Name.")]
        [StringLength(100, ErrorMessage = "The Product Group Name must be less than {1} characters.")]
        [Display(Name = "Product Group Name:")]
        public string prod_grp_name { get; set; }

        public string prod_grp_type { get; set; }
    }
}
