//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XandaPOS.Edmx
{
    using System;
    using System.Collections.Generic;
    
    public partial class POS_MASTER_TABLE_HELPER
    {
        public string helper_id { get; set; }
        public string helper_name { get; set; }
        public string helper_link_master_table { get; set; }
        public string helper_details { get; set; }
        public bool helper_active { get; set; }
    }
}
