//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XandaPOS.Edmx
{
    using System;
    using System.Collections.Generic;
    
    public partial class pos_PurchaseOrder_Sheet
    {
        public int purchase_prod_sheet_id { get; set; }
        public int purchase_order_main_id { get; set; }
        public Nullable<int> product_id { get; set; }
        public Nullable<decimal> product_order_qty { get; set; }
        public Nullable<decimal> product_receive_qty { get; set; }
        public Nullable<decimal> product_cost_actual { get; set; }
        public Nullable<int> tax_id { get; set; }
        public Nullable<decimal> tax_percent { get; set; }
        public Nullable<decimal> subtotal { get; set; }
    }
}
