//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XandaPOS.Edmx
{
    using System;
    using System.Collections.Generic;
    
    public partial class POS_WAREHOUSE_MASTER
    {
        public string warehouse_id { get; set; }
        public string warehouse_name { get; set; }
        public string warehouse_address { get; set; }
        public string warehouse_pin { get; set; }
        public string warehouse_phone { get; set; }
        public string warehouse_code { get; set; }
    }
}
