//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XandaPOS.Edmx
{
    using System;
    using System.Collections.Generic;
    
    public partial class POS_PRODUCT_MASTER
    {
        public string product_id { get; set; }
        public string product_name { get; set; }
        public string product_type { get; set; }
        public string product_group { get; set; }
        public string product_company { get; set; }
        public string product_details { get; set; }
        public string product_image_link { get; set; }
    }
}
