//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XandaPOS.Edmx
{
    using System;
    using System.Collections.Generic;
    
    public partial class POS_BRAND_MASTER
    {
        public int brand_id { get; set; }
        public string brand_name { get; set; }
        public int brand_company { get; set; }
        public Nullable<int> brand_product_group { get; set; }
    }
}
