//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XandaPOS.Edmx
{
    using System;
    using System.Collections.Generic;
    
    public partial class POS_TAX_MASTER
    {
        public int tax_id { get; set; }
        public string tax_name { get; set; }
        public string tax_description { get; set; }
        public decimal tax_percent { get; set; }
        public bool tax_active_status { get; set; }
    }
}
