//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XandaPOS.Edmx
{
    using System;
    using System.Collections.Generic;
    
    public partial class POS_PRODUCT_GROUP_MASTER
    {
        public int prod_grp_id { get; set; }
        public string prod_grp_name { get; set; }
        public string prod_grp_type { get; set; }
    }
}
