//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XandaPOS.Edmx
{
    using System;
    using System.Collections.Generic;
    
    public partial class POS_EMPLOYEE_MASTER
    {
        public string emp_id { get; set; }
        public string emp_name { get; set; }
        public string emp_addr { get; set; }
        public string emp_pin { get; set; }
        public string emp_phn { get; set; }
        public string emp_govt_id_type { get; set; }
        public string emp_govt_id_no { get; set; }
        public Nullable<System.DateTime> emp_join_date { get; set; }
        public Nullable<System.DateTime> emp_resign_date { get; set; }
    }
}
