//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XandaPOS.Edmx
{
    using System;
    using System.Collections.Generic;
    
    public partial class POS_COMPANY_MASTER
    {
        public int comp_id { get; set; }
        public string comp_name { get; set; }
        public string comp_address { get; set; }
        public string comp_pin { get; set; }
        public Nullable<int> comp_type { get; set; }
        public string comp_regn_no { get; set; }
    }
}
